Итоговое задание Спринт №6
RinaBlinova/java-kanban pull request #1
Opened 2024-04-22 11:39 UTC by RinaBlinova

История посещений сделана неограниченной по размеру.
Из истории убраны повторные просмотры. 
Написана собственная реализация связного списка с индексом по id задачи.

2024-04-22 17:37 UTC, YazykovMikhail requested changes

2024-04-22 17:37 UTC, YazykovMikhail commented on src/ru/yandex/javacource/blinova/schedule/service/implementation/InMemoryHistoryManager.java
> -        if (task == null) {
```
    if (task == null) {
            return;
        }
```

Стоитло оставить, если задача была удалена, может null прдидти в историю

2024-04-22 17:37 UTC, YazykovMikhail commented on src/ru/yandex/javacource/blinova/schedule/service/implementation/InMemoryHistoryManager.java
> +        if (history.containsKey(taskId)) {
Оптимизируем это место: 
```
        if (history.containsKey(taskId)) {
            Node existingTask = history.get(taskId);
            removeNode(existingTask);
            history.remove(taskId);
        }
```
Вместо этого, просто 
`remove(taskId);`

2024-04-22 17:37 UTC, YazykovMikhail commented on src/ru/yandex/javacource/blinova/schedule/service/implementation/InMemoryHistoryManager.java
> +    public void remove(Long id) {
А тут как раз просто:
```

	public void remove(int id) {
		final Node node = nodeMap.remove(id);
		if (node == null) {
			return;
		}
		removeNode(node);
	}
```

2024-04-22 17:37 UTC, YazykovMikhail commented on src/ru/yandex/javacource/blinova/schedule/service/implementation/InMemoryHistoryManager.java
> +    private void linkLast(Task task) {
Создавай задачу передавая сразу предыдущую таску:

```
	private void linkLast(Task task) {
		final Node node = new Node(task, tail, null);
		if (head == null) {
			head = node;
		} else {
			tail.next = node;
		}
		tail = node;
	}
```

С учетом того что конструктор выглядит так:
```
public Node(Task task, Node prev, Node next) {
			this.task = task;
			this.prev = prev;
			this.next = next;
		}

```

2024-04-22 17:37 UTC, YazykovMikhail commented on src/ru/yandex/javacource/blinova/schedule/util/Node.java
> +package ru.yandex.javacource.blinova.schedule.util;
Утилитные классы имеют статические методы и не имеют контекста, они просто принимают что то в методе и возвращают в ответ. 
Это не утилитный класс, стоит убрать его к папку к задачам или еще лучше сделать внутренним классом в InMemoryHistoryManager, потому что этот класс используется только внутри InMemoryHistoryManager и все, поэтому лучше его сделать внутреним статическим классом

2024-04-23 17:30 UTC, RinaBlinova commented on src/ru/yandex/javacource/blinova/schedule/service/implementation/InMemoryHistoryManager.java
> -        if (task == null) {
Поправила

2024-04-23 17:30 UTC, RinaBlinova commented on src/ru/yandex/javacource/blinova/schedule/service/implementation/InMemoryHistoryManager.java
> +        if (history.containsKey(taskId)) {
Поправила

2024-04-23 17:30 UTC, RinaBlinova commented on src/ru/yandex/javacource/blinova/schedule/service/implementation/InMemoryHistoryManager.java
> +    public void remove(Long id) {
Поправила

2024-04-23 17:30 UTC, RinaBlinova commented on src/ru/yandex/javacource/blinova/schedule/service/implementation/InMemoryHistoryManager.java
> +    private void linkLast(Task task) {
Поправила

2024-04-23 17:31 UTC, RinaBlinova commented on src/ru/yandex/javacource/blinova/schedule/util/Node.java
> +package ru.yandex.javacource.blinova.schedule.util;
Перенесла класс Node в InMemoryHistoryManager. Спасибо большое за помощь!

2024-04-24 08:09 UTC, merged